function createFigure()
  global Year Australia Japan
  name={'Australia','Japan'}
  createFigure(Year,[Australia,Japan],name)

function createfigure(X1,YMatrix1,name)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 14-Mar-2017 10:04:42

%% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

%% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'DisplayName',name{1});
set(plot1(2),'DisplayName',name{2},'LineStyle','--','Color',[0 0 0]);

% Create xlabel
xlabel('year');

% Create ylabel
ylabel('gas price ($US)');

box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.161274511863777 0.788299665707933 0.129411762646016 0.0921717147634487]);

