dataForecast = webread('http://api.wunderground.com/api/b728a7436f25b9f2/conditions/q/TH/Nonthaburi.json');
valForecast = dataForecast.forecast;

valRainDay = [1 1 1 1 1];

    Rain=[dataForecast.forecast.simpleforecast.forecastday(1).qpf_day.mm;...
          dataForecast.forecast.simpleforecast.forecastday(2).qpf_day.mm;...
          dataForecast.forecast.simpleforecast.forecastday(3).qpf_day.mm;...
          dataForecast.forecast.simpleforecast.forecastday(4).qpf_day.mm;...
          dataForecast.forecast.simpleforecast.forecastday(5).qpf_day.mm;...
        ];

